<a href="https://colab.research.google.com/github/KamilBienias/data-science/blob/main/training/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **numpy**

In [30]:
# https://zadania24h.wordpress.com/2018/10/17/python-biblioteki-numpy-pandas-matplotlib/

### 1. Wygeneruj losową tablice 100 x 10, która będzie reprezentować 100 punktów w 10 wymiarowej przestrzeni. Napisz funkcję, która policzy odległość euklidesową pomiędzy każdą parą punktów, czy potrafisz zrobić to w jednej linijce, bez użycia żadnych pętli/wytworników pętli? Przypomnienie, dla dwóch wektorów xx i yy odległość euklidesową liczymy z podanego wzoru.

In [31]:
import numpy as np

# tablica o wartościach całkowitych od 0 do 4
table = np.random.randint(5, size=(100, 10))
print("table[:3] =")
print(table[:3])
list_of_distances = []
for i in range(len(table)):
    for j in range(len(table)):
        if j > i:
            distance = np.linalg.norm(table[j] - table[i])
            list_of_distances.append((i, j, distance))

print("list_of_distances[:5] =")
print(list_of_distances[:5])
print
print("Tyle jest obliczonych odległości")
print(len(list_of_distances))
print("Tyle jest obliczonych odległości (na piechotę)")
print(100*99/2)

table[:3] =
[[2 2 2 4 3 4 3 0 0 0]
 [2 1 2 4 3 0 0 0 2 4]
 [1 2 3 0 0 2 1 2 1 2]]
list_of_distances[:5] =
[(0, 1, 6.782329983125268), (0, 2, 6.6332495807108), (0, 3, 6.244997998398398), (0, 4, 7.810249675906654), (0, 5, 6.244997998398398)]
Tyle jest obliczonych odległości
4950
Tyle jest obliczonych odległości (na piechotę)
4950.0


### 2. Wypełnij 100-elementową tablicę liczbami losowymi naturalnymi z zakresu [5,15] i policz liczbę wystąpień tych liczb. Która z tych liczb najczęściej występuje w tak wygenerowanej tablicy? Wskazówka: zobacz funkcje: bincount, argmax.

In [41]:
import numpy as np

# pierwszy argiment do min (zawarty), drugi to max (bez niego), trzeci to długość listy.
# Jeśli size=(m, n) to tworzy listę m elementową, której każdy element jest listą n elementową
table2 = np.random.randint(5, 16, size=100)
print(table2)

print()
bin = np.bincount(table2)
print("bin =")
print(bin)
print("Oznacza:")
for i in range(len(bin)):
    print("Liczba", i, "występuje tyle razy:", bin[i])

print()
print("Liczba", np.argmax(bin), "powtarza się najczęściej, czyli", bin[np.argmax(bin)], "razy.")

[15 10 11 14 11  6  7  6  7  8  8 13 10  6 14  8 11 13  8  8 14  9 11  5
 11 15 14 14  6  5 12  8  6 10 10  5  6  5  7  6 13 14 10 13  8 13  5 11
 14 12 11 12  5  9  6  7  5  9 11  8  5 15  8  6 13  9 13  9 12  6 11  9
 11 11 11 10 10  7  7  8  6  8 15  7  7  6 14 15 10 14 15 13 12 10 15 15
  9 12  5  5]

bin =
[ 0  0  0  0  0 10 12  8 11  7  9 12  6  8  9  8]
Oznacza:
Liczba 0 występuje tyle razy: 0
Liczba 1 występuje tyle razy: 0
Liczba 2 występuje tyle razy: 0
Liczba 3 występuje tyle razy: 0
Liczba 4 występuje tyle razy: 0
Liczba 5 występuje tyle razy: 10
Liczba 6 występuje tyle razy: 12
Liczba 7 występuje tyle razy: 8
Liczba 8 występuje tyle razy: 11
Liczba 9 występuje tyle razy: 7
Liczba 10 występuje tyle razy: 9
Liczba 11 występuje tyle razy: 12
Liczba 12 występuje tyle razy: 6
Liczba 13 występuje tyle razy: 8
Liczba 14 występuje tyle razy: 9
Liczba 15 występuje tyle razy: 8

Liczba 6 powtarza się najczęściej, czyli 12 razy.


In [ ]:
# https://brain.fuw.edu.pl/edu/index.php/PPy3/NumPy

### 1. Napisz funkcję zastap_zera(A, x), która zwraca tablicę utworzoną z tablicy A (o dowolnym kształcie) poprzez zastąpienie wszystkich elementów równych zero liczbą x. Sama tablica A powinna pozostać niezmieniona.

In [66]:
import numpy as np

A = np.array([[4, 0, 2], [0, -3, 9]])
print("A =")
print(A)

amount_of_elements = sum([len(listInA) for listInA in A])
print()
print("Liczba elementów tablicy A =", amount_of_elements)

def zastap_zera(A, x):
    # samo B = A nie tworzy kopii, bo zmieniając elementy z B zmienią się też z A
    B = np.copy(A)
    # przechodzi po numerach wierzy w B, czyli 0 i 1
    for row_number in range(len(B)):
        # w i-tym wierszu przechodzi po numerach jego elementów, czyli 0,1,2
        for column_number in range(len(B[row_number])):
            if B[row_number][column_number] == 0:
                B[row_number][column_number] = x
    return B

B = zastap_zera(A, 15)

print()
print("B =")
print(B)

print()
print("A =")
print(A)

A =
[[ 4  0  2]
 [ 0 -3  9]]

Liczba elementów tablicy A = 6

B =
[[ 4 15  2]
 [15 -3  9]]

A =
[[ 4  0  2]
 [ 0 -3  9]]


### 2. Napisz funkcję wysrodkuj(A), która modyfikuje tablicę A (o dowolnym kształcie) w taki sposób, że od każdego jej elementu odejmuje średnią arytmetyczną wszystkich elementów A.

In [67]:
import numpy as np

A = np.array([[4, 0, 2], [0, -3, 9]])
print("A =")
print(A)

print()
srednia = np.mean(A)
print("Średnia ze wszystkich elementów =", srednia)

def wysrodkuj(A):
    for row_number in range(len(A)):
        for column_number in range(len(A[row_number])):
            A[row_number][column_number] = A[row_number][column_number] - srednia
    return A

print()
print("Tablica A po odjęciu średniej od każdego jej elementu")
A = wysrodkuj(A)
print(A)

A =
[[ 4  0  2]
 [ 0 -3  9]]

Średnia ze wszystkich elementów = 2.0

Tablica A po odjęciu średniej od każdego jej elementu
[[ 2 -2  0]
 [-2 -5  7]]


### 3. Dla tablicy kwadratowej A (dowolnego rozmiaru większego niż 1) stworzyć tablicę jednowymiarową, której k-ty element to suma elementów k-tej kolumny tablicy A leżących poniżej głównej przekątnej.

In [70]:
import numpy as np

A = np.array([[5, 1, 3, 4], [2, 3, 6, 3], [7, 9, 1, 3], [8, 2, 4, 1]])
print("A =")
print(A)

sumy_kolumn = []
# przechodzi po numerach kolumn
for column_number in range(len(A)):
    suma_kolumny = 0
    # przechodzi po numerach wierszy
    for row_number in range(len(A)):
        suma_kolumny = suma_kolumny + A[row_number][column_number]
    sumy_kolumn.append(suma_kolumny)

print()
print("Sumy wszystkich kolumn")
print(sumy_kolumn) 

sumy_kolumn_pod_przekatna = []
# przechodzi po numerach kolumn
for column_number in range(len(A)):
    suma_kolumny = 0
    # przechodzi po numerach wierszy
    for row_number in range(len(A)):
        if row_number > column_number:
            suma_kolumny = suma_kolumny + A[row_number][column_number]
    sumy_kolumn_pod_przekatna.append(suma_kolumny)

print()
print("Sumy wszystkich kolumn pod przekątną")
print(sumy_kolumn_pod_przekatna) 

A =
[[5 1 3 4]
 [2 3 6 3]
 [7 9 1 3]
 [8 2 4 1]]

Sumy wszystkich kolumn
[22, 15, 14, 11]

Sumy wszystkich kolumn pod przekątną
[17, 11, 4, 0]


### 4. Napisz funkcję, która w minimalnej liczbie kroków tworzy (i zwraca) kwadratową tablicę NumPy zawierającą na przemian jedynki i zera, o dowolnym - zadanym przez argument wywołania - rozmiarze, w postaci:

In [76]:
def naprzemian(size):
    A = np.zeros((size, size))
    # przechodzi przez numery wierszy od 0 do size-1
    for row_number in range(size):
        # jeśli numer wiersza jest parzysty
        if row_number % 2 == 0:
            # przechodzi przez numery elementów w wierszu row_number
            for element_number in range(size):
                # jeśli numer elementu jest parzysty
                if element_number % 2 == 0:
                    # to wstawia jedynkę
                    A[row_number][element_number] = 1
        # jeśli numer wiersza jest nieparzysty
        elif row_number % 2 == 1:
            # przechodzi przez numery elementów w wierszu row_number
            for element_number in range(size):
                # jeśli numer elementu jest nieparzysty
                if element_number % 2 == 1:
                    # to wstawia jedynkę
                    A[row_number][element_number] = 1
    return A

naprzemian(8)

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])