<a href="https://colab.research.google.com/github/KamilBienias/data-science/blob/main/training/reg_wielomianowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [363]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# ilość próbek
m = 100

# podobny do przykładu z dokumentacji,
# ale uogólniłem na m próbek i dorzuciłem y
X = np.arange(m*2).reshape(m, 2)
X
# X1, X2

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9],
       [ 10,  11],
       [ 12,  13],
       [ 14,  15],
       [ 16,  17],
       [ 18,  19],
       [ 20,  21],
       [ 22,  23],
       [ 24,  25],
       [ 26,  27],
       [ 28,  29],
       [ 30,  31],
       [ 32,  33],
       [ 34,  35],
       [ 36,  37],
       [ 38,  39],
       [ 40,  41],
       [ 42,  43],
       [ 44,  45],
       [ 46,  47],
       [ 48,  49],
       [ 50,  51],
       [ 52,  53],
       [ 54,  55],
       [ 56,  57],
       [ 58,  59],
       [ 60,  61],
       [ 62,  63],
       [ 64,  65],
       [ 66,  67],
       [ 68,  69],
       [ 70,  71],
       [ 72,  73],
       [ 74,  75],
       [ 76,  77],
       [ 78,  79],
       [ 80,  81],
       [ 82,  83],
       [ 84,  85],
       [ 86,  87],
       [ 88,  89],
       [ 90,  91],
       [ 92,  93],
       [ 94,  95],
       [ 96,  97],
       [ 98,  99],
       [100, 101],
       [102, 103],
       [104,

In [364]:
# tak było na początku
# X1 = np.array([X[0][0], X[1][0], X[2][0]])

X1_list = []
for i in range(len(X)):
    element = X[i][0]
    X1_list.append(element)
X1 = np.array(X1_list)
X1

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [365]:
# tak było na początku
# X1 = np.array([X[0][1], X[1][1], X[2][1])

X2_list = []
for i in range(len(X)):
    element = X[i][1]
    X2_list.append(element)
X2 = np.array(X2_list)
X2

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199])

In [366]:
# y bez szumu
y_clean = -X1*X1 - X1*X2 + X2*X2
y_clean

array([     1,     -1,    -11,    -29,    -55,    -89,   -131,   -181,
         -239,   -305,   -379,   -461,   -551,   -649,   -755,   -869,
         -991,  -1121,  -1259,  -1405,  -1559,  -1721,  -1891,  -2069,
        -2255,  -2449,  -2651,  -2861,  -3079,  -3305,  -3539,  -3781,
        -4031,  -4289,  -4555,  -4829,  -5111,  -5401,  -5699,  -6005,
        -6319,  -6641,  -6971,  -7309,  -7655,  -8009,  -8371,  -8741,
        -9119,  -9505,  -9899, -10301, -10711, -11129, -11555, -11989,
       -12431, -12881, -13339, -13805, -14279, -14761, -15251, -15749,
       -16255, -16769, -17291, -17821, -18359, -18905, -19459, -20021,
       -20591, -21169, -21755, -22349, -22951, -23561, -24179, -24805,
       -25439, -26081, -26731, -27389, -28055, -28729, -29411, -30101,
       -30799, -31505, -32219, -32941, -33671, -34409, -35155, -35909,
       -36671, -37441, -38219, -39005])

In [367]:
# szumem jest m liczb z rozkładu N(0,200)
noise = 200 * np.random.randn(m)
noise

array([  84.79274479,  187.20404683,   80.42167187,  424.03058956,
         81.23837455,  118.31210181, -269.24181687, -391.49231852,
        245.68829145,  511.57533139, -199.57870771,  267.92471192,
         65.05515081, -184.80937759,  -36.22302484,  116.91692575,
       -319.86477388, -204.34676386, -339.97686053,   84.40296908,
        328.13472194,  -75.69822259, -198.74804704, -114.65874705,
       -364.3948836 , -135.00596088,    4.94444089,  200.60205625,
        -47.00052393,   17.73805185,  178.13438749, -138.34930966,
       -156.12861754,  138.22343124,  304.19928266,  -47.38697093,
         18.56734621,  -51.59736159, -168.85894342, -287.54330424,
       -206.79524324, -160.22353236,   69.84865358,  152.72381219,
        316.53808268,   19.08022612,   70.26567744, -102.91739091,
        200.00525315,  -19.84907274,  121.94526992,   59.91216082,
         54.99370051, -200.61710285,   21.38919755,  -81.01882227,
        210.31040075,  -72.52864578,  140.90551909,  -57.45873

In [368]:
# y_true
y_true = -X1*X1 - X1*X2 + X2*X2 + noise
y_true

array([ 8.57927448e+01,  1.86204047e+02,  6.94216719e+01,  3.95030590e+02,
        2.62383746e+01,  2.93121018e+01, -4.00241817e+02, -5.72492319e+02,
        6.68829145e+00,  2.06575331e+02, -5.78578708e+02, -1.93075288e+02,
       -4.85944849e+02, -8.33809378e+02, -7.91223025e+02, -7.52083074e+02,
       -1.31086477e+03, -1.32534676e+03, -1.59897686e+03, -1.32059703e+03,
       -1.23086528e+03, -1.79669822e+03, -2.08974805e+03, -2.18365875e+03,
       -2.61939488e+03, -2.58400596e+03, -2.64605556e+03, -2.66039794e+03,
       -3.12600052e+03, -3.28726195e+03, -3.36086561e+03, -3.91934931e+03,
       -4.18712862e+03, -4.15077657e+03, -4.25080072e+03, -4.87638697e+03,
       -5.09243265e+03, -5.45259736e+03, -5.86785894e+03, -6.29254330e+03,
       -6.52579524e+03, -6.80122353e+03, -6.90115135e+03, -7.15627619e+03,
       -7.33846192e+03, -7.98991977e+03, -8.30073432e+03, -8.84391739e+03,
       -8.91899475e+03, -9.52484907e+03, -9.77705473e+03, -1.02410878e+04,
       -1.06560063e+04, -

In [369]:
poly = PolynomialFeatures(2)
X_poly_2 = poly.fit_transform(X)
X_poly_2
# 1, X1, X2, X1**2, X1*X2, X2**2

array([[1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 6.0000e+00,
        9.0000e+00],
       [1.0000e+00, 4.0000e+00, 5.0000e+00, 1.6000e+01, 2.0000e+01,
        2.5000e+01],
       [1.0000e+00, 6.0000e+00, 7.0000e+00, 3.6000e+01, 4.2000e+01,
        4.9000e+01],
       [1.0000e+00, 8.0000e+00, 9.0000e+00, 6.4000e+01, 7.2000e+01,
        8.1000e+01],
       [1.0000e+00, 1.0000e+01, 1.1000e+01, 1.0000e+02, 1.1000e+02,
        1.2100e+02],
       [1.0000e+00, 1.2000e+01, 1.3000e+01, 1.4400e+02, 1.5600e+02,
        1.6900e+02],
       [1.0000e+00, 1.4000e+01, 1.5000e+01, 1.9600e+02, 2.1000e+02,
        2.2500e+02],
       [1.0000e+00, 1.6000e+01, 1.7000e+01, 2.5600e+02, 2.7200e+02,
        2.8900e+02],
       [1.0000e+00, 1.8000e+01, 1.9000e+01, 3.2400e+02, 3.4200e+02,
        3.6100e+02],
       [1.0000e+00, 2.0000e+01, 2.1000e+01, 4.0000e+02, 4.2000e+02,
        4.4100e+02],
       [1.0000e+00, 2

In [370]:
from sklearn.linear_model import LinearRegression

regressor_poly_2 = LinearRegression()
regressor_poly_2.fit(X_poly_2, y_true)

y_pred_2 = regressor_poly_2.predict(X_poly_2)
y_pred_2

array([ 2.57835570e+01,  2.27431597e+01,  1.17322747e+01, -7.24909791e+00,
       -3.42009582e+01, -6.91233063e+01, -1.12016142e+02, -1.62879465e+02,
       -2.21713276e+02, -2.88517575e+02, -3.63292361e+02, -4.46037636e+02,
       -5.36753397e+02, -6.35439647e+02, -7.42096384e+02, -8.56723609e+02,
       -9.79321321e+02, -1.10988952e+03, -1.24842821e+03, -1.39493738e+03,
       -1.54941705e+03, -1.71186720e+03, -1.88228784e+03, -2.06067896e+03,
       -2.24704058e+03, -2.44137268e+03, -2.64367527e+03, -2.85394835e+03,
       -3.07219191e+03, -3.29840596e+03, -3.53259050e+03, -3.77474553e+03,
       -4.02487104e+03, -4.28296705e+03, -4.54903354e+03, -4.82307052e+03,
       -5.10507798e+03, -5.39505594e+03, -5.69300438e+03, -5.99892331e+03,
       -6.31281272e+03, -6.63467263e+03, -6.96450302e+03, -7.30230390e+03,
       -7.64807527e+03, -8.00181712e+03, -8.36352947e+03, -8.73321230e+03,
       -9.11086561e+03, -9.49648942e+03, -9.89008371e+03, -1.02916485e+04,
       -1.07011838e+04, -

In [371]:
import pandas as pd

df = pd.DataFrame({
    "X1": X1,
    "X2": X2,
    "y_clean": y_clean,
    "y_true": y_true,
    "y_pred": y_pred_2,
    "y_pred_2 - y_clean": y_pred_2 - y_clean
})
df

X1   X2  y_clean        y_true        y_pred  y_pred_2 - y_clean
0     0    1        1     85.792745     25.783557           24.783557
1     2    3       -1    186.204047     22.743160           23.743160
2     4    5      -11     69.421672     11.732275           22.732275
3     6    7      -29    395.030590     -7.249098           21.750902
4     8    9      -55     26.238375    -34.200958           20.799042
..  ...  ...      ...           ...           ...                 ...
95  190  191   -35909 -35873.804710 -35851.281669           57.718331
96  192  193   -36671 -36581.511833 -36611.518396           59.481604
97  194  195   -37441 -37254.240846 -37379.725610           61.274390
98  196  197   -38219 -38369.438150 -38155.903312           63.096688
99  198  199   -39005 -39113.684317 -38940.051502           64.948498

[100 rows x 6 columns]

In [372]:
import plotly.express as px

fig = px.scatter_3d(df, x='X1', y='X2', z='y_true', labels={"y_true": "prawdziwy"})
fig2 = px.line_3d(df, x='X1', y='X2', z='y_pred', labels={"y_pred": "predykcja"})
fig.update_traces(marker_color='yellow')
fig.add_trace(fig2.data[0])
fig.show()
# trzeba przybliżyć żeby zobaczyć niebieską linię predykcji